### ISSUE TITLE
Question about IDidChangeConfigurationHandler

### ISSUE THREAD

**Issue by gep13** [OmniSharp/csharp-language-server-protocol#124]
I am trying to implement the IDidChangeConfigurationHandler interface, for use within a Language Server that we are creating here:

https://github.com/gep13/chocolatey-vscode

For validating the Chocolatey Nuspec file when editing within VSCode.  In general, things have been going very well with this implementation thanks to some input from @mholo65.  The problem stems from the fact that ideally, I would like to have configuration in the following format:

![image](https://user-images.githubusercontent.com/1271146/53596780-770e3b80-3b98-11e9-8c19-124d0f9a7c95.png)

However, when I try to run the Language Server with this configuration, I get the following error:

```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Unexpected token when deserializing object: String. Path 'params.settings.nuspec.suppressedRules[0]', line 1, position 123.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params) in /_/src/Server/LspRequestRouter.cs:line 77
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request) in /_/src/JsonRpc/InputHandler.cs:line 198
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream() in /_/src/JsonRpc/InputHandler.cs:line 120
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Digging into the tests, it looks like it is expected that the JSON values are only boolean, number and string, rather than the more complex JSON types:

https://github.com/OmniSharp/csharp-language-server-protocol/blob/0832add57b942fada096b8bfe0c266e87d84cfe3/test/Lsp.Tests/Models/DidChangeConfigurationParamsTests.cs#L18-L23

However, the specification for the Language Server Protocol suggests that it should be of type `any`:

https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration

Is there a reason for not implementing the settings object directly as a JObject, or something similar?

I could work around this using a configuration similar to the following:

![image](https://user-images.githubusercontent.com/1271146/53597074-2519e580-3b99-11e9-90c3-450353807cf3.png)

However, I was hoping to expand to having a configuration similar to the following extension:

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

/cc @tintoy @david-driscoll

**Comment by tintoy** [comment]
FWIW, I wound up working around that problem by defining my own custom handler that _does_ use `JToken` :)

https://github.com/tintoy/msbuild-project-tools-server/blob/master/src/LanguageServer.Engine/CustomProtocol/DidChangeConfigurationSettings.cs

**Comment by gep13** [comment]
@tintoy thanks for getting back to me!!

That looks like exactly what I want/need, if there are no objections, I will unashamedly borrow that 😄 

Do you know if there is a reason that the OOTB implementation doesn't provide something like this?

**Comment by tintoy** [comment]
You’re welcome to - it’s MIT licensed :)

I suspect the answer is historical reasons. Not sure exactly what they are though.

**Comment by gep13** [comment]
>@tintoy said...
You’re welcome to - it’s MIT licensed :)

I did check that before, and I am very grateful that this is how it is licensed.  Correct/grateful attribution will be added to the project though.

**Comment by gep13** [comment]
@tintoy do you know if something has changed in this area...

![image](https://user-images.githubusercontent.com/1271146/53623493-2973ec00-3bf5-11e9-825f-5384347c840d.png)

Your project is using 0.7.9 of OmniSharp and mine is using 0.11.3.

**Comment by tintoy** [comment]
Yeah probably - I had to make significant extensions to the LSP library for my extension (required functionality wasn’t present at the time) so I haven’t had time to upgrade yet (newer versions are so different from older ones that it’s pradtically a rewrite in some areas).

Basic principle still applies I believe, but interface names might be slightly different :)

**Comment by tintoy** [comment]
Take a look at the interface definition for the configuration handler in the LSP library - maybe use that as the basis for your new handler?

**Comment by gep13** [comment]
@tintoy I have "something" compiling 😄 just away to test it just now.  Seems like `INotificationHandler` is now `IJsonRpcNotificationHandler`.

**Comment by tintoy** [comment]
I think this is what you're looking for...

https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/src/Protocol/Workspace/Server/IDidChangeConfigurationHandler.cs

**Comment by tintoy** [comment]
Just define your own parameters model and use that instead.

**Comment by gep13** [comment]
Going to have to play with this later, as I have other things that I need to be getting on with 😄 Thanks for your help so far though.

I have something that compiles, and doesn't seem to generate any runtime errors, but changing the configuration settings isn't causing anything to be triggered.  Will play again later.

**Comment by gep13** [comment]
@tintoy scratch that...

I have it working!  Or at least, I think I do 😄 

I will attempt to finalize a PR for my repo, and if you have some time, I might ask that you and @mholo65 have a look at it to make sure I am not doing anything stupid 🐱

**Comment by gep13** [comment]
@tintoy I have a WIP PR here, where I have the basics in place:

https://github.com/gep13/chocolatey-vscode/pull/135

Would you have some time for a review at some point?  Thanks!

**Comment by david-driscoll** [comment]
definitely still a bug to be fixed... I'm going to try and fix this tonight or this weekend.
