### ISSUE TITLE
Tests in VS2017

### ISSUE THREAD

**Issue by Lercher** [OmniSharp/csharp-language-server-protocol#13]
It's not going away since I joined, and I don't find the cause for the duplicate key. Any helpful thoughts?
````
------ Discover test started ------
Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
SampleServer.dll is built for Framework FrameworkCore10 and Platform X64.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
[xUnit.net 00:00:00.4003044]   Discovering: JsonRpc.Tests
[xUnit.net 00:00:00.8653768]   Discovered:  JsonRpc.Tests
[xUnit.net 00:00:01.1695729]   Discovering: Lsp.Tests
[xUnit.net 00:00:02.4686640]   Discovered:  Lsp.Tests
A test with the same name 'JsonRpc.Tests.HandlerResolverTests.Should_Have_CorrectParams (0b3c812df8e74c46b3132be96fe7eca4473a1976)' already exists. This test is not added to the test window.
========== Discover test finished: 174 found (0:00:02,8958999) ==========
------ Run test started ------
[xUnit.net 00:00:00.3931256]   Discovering: JsonRpc.Tests
[xUnit.net 00:00:01.2304602]   Discovered:  JsonRpc.Tests
[xUnit.net 00:00:01.2890534] JsonRpc.Tests: Catastrophic failure: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
[xUnit.net 00:00:01.5023966]   Discovering: Lsp.Tests
[xUnit.net 00:00:03.4844202]   Discovered:  Lsp.Tests
[xUnit.net 00:00:03.4875018]   Starting:    Lsp.Tests
[xUnit.net 00:00:05.7481184]   Finished:    Lsp.Tests
========== Run test finished: 135 run (0:00:06,0399637) ==========
````
... instead of 174. I always have to start the remaining tests separately. My xUnit.* is 2.3.0-beta1-build3642.

Thanks, Martin

**Comment by david-driscoll** [comment]
Yeah there is an issue with xunit, https://github.com/xunit/xunit/issues/1233, it's been fixed now.  So we should be able to update to beta2 and have things work.

**Comment by Lercher** [comment]
Cool, can't await it. :-)

**Comment by david-driscoll** [comment]
Thing we fixed this!
