### ISSUE TITLE
v0.13.0 unable to serialize BooleanOrConverter

### ISSUE THREAD

**Issue by mholo65** [OmniSharp/csharp-language-server-protocol#159]
Looks like I released to soon. Will investigate and create 0.13.1

// cc @david-driscoll 

```
Application: OmniSharp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at Newtonsoft.Json.Linq.JValue.GetValueType(System.Nullable`1<Newtonsoft.Json.Linq.JTokenType>, System.Object)
   at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters.BooleanOrConverter.WriteJsonGeneric[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Newtonsoft.Json.JsonWriter, OmniSharp.Extensions.LanguageServer.Protocol.Models.BooleanOr`1<System.__Canon>, Newtonsoft.Json.JsonSerializer)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters.BooleanOrConverter.WriteJson(Newtonsoft.Json.JsonWriter, System.Object, Newtonsoft.Json.JsonSerializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(Newtonsoft.Json.JsonWriter, Newtonsoft.Json.JsonConverter, System.Object, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(Newtonsoft.Json.JsonWriter, System.Object, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(Newtonsoft.Json.JsonWriter, System.Object, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(Newtonsoft.Json.JsonWriter, System.Object, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(Newtonsoft.Json.JsonWriter, System.Object, System.Type)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(Newtonsoft.Json.JsonWriter, System.Object, System.Type)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(System.Object, System.Type, Newtonsoft.Json.JsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Serializer.SerializeObject(System.Object)
   at OmniSharp.Extensions.JsonRpc.OutputHandler.ProcessOutputQueue()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mholo65** [comment]
Exception details:
```
System.ArgumentException
  HResult=0x80070057
  Message=Could not determine JSON object type for type OmniSharp.Extensions.LanguageServer.Protocol.Server.Capabilities.RenameOptions.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
   at Newtonsoft.Json.Linq.JValue..ctor(Object value)
   at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters.BooleanOrConverter.WriteJsonGeneric[T](JsonWriter writer, BooleanOr`1 value, JsonSerializer serializer) in C:\Users\mb\src\gh\csharp-language-server-protocol\src\Protocol\Serialization\Converters\BooleanOrConverter.cs:line 28
```
