### ISSUE TITLE
Null ref exception in Client lib

### ISSUE THREAD

**Issue by TylerLeonhardt** [OmniSharp/csharp-language-server-protocol#210]
It only seems to happen on my machine (running in CI) but here's what I get:

```
Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters.CommandOrCodeActionConverter.ReadJson(JsonReader reader, Type objectType, CommandOrCodeAction existingValue, Boolean hasExistingValue, JsonSerializer serializer) in /_/src/Protocol/Serialization/Converters/CommandOrCodeActionConverter.cs:line 28
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Client.Protocol.LspConnection.SendRequest[TResponse](String method, Object request, CancellationToken cancellationToken)
   at PowerShellEditorServices.Test.E2E.LanguageServerProtocolMessageTests.CanSendCodeActionRequest() in /Users/tyleonha/Code/PowerShell/vscode/PowerShellEditorServices/test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs:line 642
```

The code in question:

https://github.com/OmniSharp/csharp-language-server-protocol/blob/c4fbf3478272f7bfedbe48e45d311fd3cfaf4b85/src/Protocol/Serialization/Converters/CommandOrCodeActionConverter.cs#L28

Here was my request:
```csharp
await LanguageClient.SendRequest<CommandOrCodeActionContainer>(
                    "textDocument/codeAction",
                    new CodeActionParams
                    {
                        TextDocument = new TextDocumentIdentifier(
                            new Uri(filePath, UriKind.Absolute)),
                        Range = new Range
                        {
                            Start = new Position
                            {
                                Line = 0,
                                Character = 0
                            },
                            End = new Position
                            {
                                Line = 0,
                                Character = 3
                            }
                        },
                        Context = new CodeActionContext
                        {
                            Diagnostics = new Container<Diagnostic>(Diagnostics)
                        }
                    });
```

**Comment by TylerLeonhardt** [comment]
cc @tintoy

**Comment by TylerLeonhardt** [comment]
I feel like the problem is probably here:

https://github.com/OmniSharp/csharp-language-server-protocol/blob/c4fbf3478272f7bfedbe48e45d311fd3cfaf4b85/src/Protocol/Serialization/Converters/CommandOrCodeActionConverter.cs#L31

What happens if `command` doesn't exist?

**Comment by tintoy** [comment]
Yep - that sounds correct to me. I’ll take a look at this in an hour or 2 (need my morning coffee first 😉)
