### ISSUE TITLE
Starting a language server in VS Code with no open folders takes down the server

### ISSUE THREAD

**Issue by kvarv** [OmniSharp/csharp-language-server-protocol#345]
Starting a language server in VS Code with no open folders takes down the server.

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'inner')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Join[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerWorkspaceFolderManager.<Refresh>b__8_2(Container`1 workspaceFolders)
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerWorkspaceFolderManager.OmniSharp.Extensions.LanguageServer.Protocol.Server.IOnLanguageServerStarted.OnStarted(ILanguageServer server, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.Initialize(CancellationToken token)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(LanguageServerOptions options, IServiceProvider outerServiceProvider, CancellationToken cancellationToken)
```

**Comment by david-driscoll** [comment]
@kvarv thanks for the report, I was able to track down the null ref and added some additional tests in #346
